
/**
Constructor
Do not call Function in Constructor.
*/
class TestFlexLayout()
{
	super();

	//TODO:edit here

}
extends AView;


function TestFlexLayout*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestFlexLayout*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestFlexLayout*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
