
/**
Constructor
Do not call Function in Constructor.
*/
class TestAutoSizeView()
{
	super();

	//TODO:edit here

}
extends AView;


function TestAutoSizeView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestAutoSizeView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestAutoSizeView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
