
/**
Constructor
Do not call Function in Constructor.
*/
class TestFlexLayout3()
{
	super();

	//TODO:edit here

}
extends AView;


function TestFlexLayout3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestFlexLayout3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestFlexLayout3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
