
/**
Constructor
Do not call Function in Constructor.
*/
class TestFlexLayout2()
{
	super();

	//TODO:edit here

}
extends AView;


function TestFlexLayout2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestFlexLayout2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestFlexLayout2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
