
/**
Constructor
Do not call Function in Constructor.
*/
class TestGridLayout()
{
	super();

	//TODO:edit here

}
extends AView;


function TestGridLayout*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestGridLayout*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestGridLayout*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
