
/**
Constructor
Do not call Function in Constructor.
*/
class TestLayout()
{
	super();

	//TODO:edit here

}
extends AView;


function TestLayout*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestLayout*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestLayout*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
