
/**
Constructor
Do not call Function in Constructor.
*/
class TestGridLayoutView()
{
	super();

	//TODO:edit here

}
extends AView;


function TestGridLayoutView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestGridLayoutView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestGridLayoutView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
